### ISSUE TITLE
Demultiplexing step taking very long

### ISSUE THREAD

**Issue by BournSupremacy** [odomlab2/sci-rocket#11]
Hi Job!

I'm currently trying to run a NovaSeq6000 dataset through the pipeline but I am getting stuck at the demultiplexing step where the experiments are demuxed in 12 different parts. Currently, the job resources for each part are set to 2.5 days, 24 GB, 4 nodes. However, the jobs are running extremely slowly. Based on file sizes from the `raw_reads` dir, only 1/10 of the sequences have been demuxed in 20 hours, so I'm sure the jobs will timeout at 2.5 days. Is this expected or abnormal? Can it be fixed by changing the resources? Or is there potentially something wrong with the data? It is also a hashed dataset, so we are also using the hashing part of the pipeline. Could this also be a problem? Any thoughts would be appreciated!

**Comment by J0bbie** [comment]
Hi Jess,

Could you try with the new release and see if it works now?
It should be a whole lot faster now.

Best,

Job
