### ISSUE TITLE
Add % intronic reads

### ISSUE THREAD

**Issue by lsaund11** [odomlab2/sci-rocket#14]
Hopefully this is something that starSolo already provides and can be easily added to the dashboard. It would be useful to know % intronic reads for various QC and downstream applications (and especially for comparing whole cell to nuclear transcriptome data).

**Comment by J0bbie** [comment]
Added metrics to sci-dash, based on the numbers found in the sample/cell-specific STARSolo Cellreads.stats:
https://github.com/alexdobin/STAR/issues/1501
