### ISSUE TITLE
python dependencies modules: requiring manual installation

### ISSUE THREAD

**Issue by plhm** [odomlab2/sci-rocket#19]
Hey, J0bbie.

I've been able to make progress down the pipeline. I'm currently trying to run your demultiplexing steps, which rely on a few python scripts. It seems that not all modules needed for the sci-rocket pipeline are installed by default when using the snakemake pipeline.

These were my steps up to this point:
```git clone https://github.com/odomlab2/sci-rocket
micromamba create -c conda-forge -c bioconda --prefix /path/to/snakemake snakemake
micromamba activate snakemake
module load anaconda
```

And to run the workflow:

```cd /path/to/workflow/
snakemake --use-conda --cores 12 --configfile /path/to/config.yaml
```

At first, I got a message saying that 'pandas' was not installed. I then installed it with micromamba.
Next, another package popped up, then I went through all your python files and sequentially attempted ot install them with 'micromamba install <package>.' By default, however, micromamba install the latest python, which is 3.12. pysam is not compatible with python 3.12, which means I'll have to re-install snakemake.

All that to say that it might be worth checking all packages and dependencies you're using and hardcode it in your snakefile. Would that be feasible? I think it'd make it easier on less experienced users.

**Comment by plhm** [comment]
Quick follow up:

I unistalled sci-rocket, and re-installed with the following set up, which seems to have fixed the issue:
`micromamba create -c conda-forge -c bioconda --prefix /path/to/snakemake snakemake python=3.10`

**Comment by plhm** [comment]
Okay, so I ended up having to install the packages manually. These are the ones I had to install up to this point (i.e. running demux_rocket.py):

`conda install pandas`
`conda install -c r -c bioconda pysam`
`conda install -c bioconda frozendict`
`conda install -c rapidfuzz`

**Comment by plhm** [comment]
Hey, J0bbie, here is how I ran the command:

`scirocket_folder=/path/to/workflow`
`echo "Load modules."`
`micromamba activate /path/to/snakemake`
`echo "Move into workflow folder."`
`cd $scirocket_folder`
`echo "Move into sci-rocket folder."`
`snakemake --use-conda --cores 12 \`
`  --configfile /path/to/config.yaml`

Thus it should be bringing up the conda environment, but that doesn't seem to be doing it for me.

**Comment by J0bbie** [comment]
Hmm, that's weird. Seems to be the right commands.
Are you running it on a cluster (LSF or SLURM etc.) or locally? If so, you might want to take a look at the `--profile` command.

It might also be that it's using another server-wide python installation whilst inside the environment.

**Comment by plhm** [comment]
Honestly, that's what I figure is going on. Now I have all the dependencies installed, so it is not much of a big deal. That said, here is how I am running the code, just in case someone ever runs into the same issue:

`echo "Load modules."`
`module load mamba`
`conda config --set channel_priority strict`
`micromamba activate /path/to/snakemake`

`echo "Move into workflow folder."`
`cd $scirocket_folder`

`echo "Move into sci-rocket folder."`
`snakemake --use-conda --cores 12 \`
`  --configfile /path/to/config.yaml`

**Comment by plhm** [comment]
Yeah, I'll go ahead and close this one. I think it has something to do with how the cluster I work with is structured, which generates quite a bit of clunkiness.
I ended up figuring out somethng that works for me, but folks will have to figure out what works for them by themselves.
