### ISSUE TITLE
starSolo_align files Missing

### ISSUE THREAD

**Issue by plhm** [odomlab2/sci-rocket#21]
Hey, J0bbie.

Running STAR with the latest set up is making the pipeline crash for me. Here is what I'm seeing:

```
Job 32: Aligning reads with STARSolo (guppy).
Reason: Missing output files: sci-test/alignment/guppy_zfish_Aligned.sortedByCoord.out.bam

Activating conda environment: .snakemake/conda/5c2479eb25e9f3ac81cd69cc2dc29410_
Waiting at most 5 seconds for missing files.
MissingOutputException in rule starSolo_align in file /sfs/gpfs/tardis/project/kyathit/software/sci-rocket/workflow/rules/step3_alignment.smk, line 67:
Job 32  completed successfully, but some output files are missing. Missing files after 5 seconds. This might be due to filesystem latency. If that is the case, consider to increase the wait time with --latency-wait:
sci-test/alignment/guppy_zfish__STARtmp
```

Here is the output from 'star_align_sci-test_guppy_zfish.log,' the log file:

```
/sfs/weka/scratch/uzt9rb/nINqwazh/sci-rocket/.snakemake/conda/5c2479eb25e9f3ac81cd69cc2dc29410_/bin/STAR-avx2 --soloMultiMappers EM --outSAMmultNmax 1 --outSAMstrandField intronMotif --outSAMunmapped Within --outSAMattributes NH HI AS nM NM MD jM jI MC ch XS CR UR GX GN sM --genomeDir resources/index_star/zfish --runThreadN 12 --readFilesIn sci-test/fastp/guppy_R2.fastq.gz sci-test/fastp/guppy_R1.fastq.gz --readFilesCommand zcat --soloFeatures GeneFull_Ex50pAS --soloType CB_UMI_Complex --soloCBmatchWLtype Exact --soloCellReadStats Standard --soloCBposition 0_0_0_9 0_10_0_19 0_20_0_29 0_30_0_39 --soloUMIposition 0_40_0_47 --soloCBwhitelist sci-test/demux_reads/sci-test_whitelist_p7.txt sci-test/demux_reads/sci-test_whitelist_p5.txt sci-test/demux_reads/sci-test_whitelist_ligation.txt sci-test/demux_reads/sci-test_whitelist_rt.txt --soloCellFilter CellRanger2.2 12000 0.99 10 --outSAMtype BAM SortedByCoordinate --outFileNamePrefix sci-test/alignment/guppy_zfish_
        STAR version: 2.7.11a   compiled: 2023-09-15T02:58:53+0000 :/opt/conda/conda-bld/star_1694746407721/work/source
Dec 22 21:40:07 ..... started STAR run
Dec 22 21:40:07 ..... loading genome
Dec 22 21:40:20 ..... started mapping
Dec 22 22:20:05 ..... finished mapping
Dec 22 22:20:06 ..... started Solo counting
Dec 22 22:21:41 ..... finished Solo counting
Dec 22 22:21:41 ..... started sorting BAM
Dec 22 22:25:12 ..... finished successfully
```

I was wondering if you've seen similar issues, or if you have the previous set up, so that I can try running it and seeing if I get the same error message.

**Comment by plhm** [comment]
Hello there, J0bbie.

I believe I figured out what was the issue.
It seems like the Snakemake pipeline was looking for a temporary folder that STAR makes after the STAR run was completed. This was making the pipeline crash, even though STAR had ran without any problems.

I was able to get rid of this message - and hopefully fix the problem - by commenting out the following lines:
```
#        dir_tmp=temp(
#            directory("{experiment_name}/alignment/{sample_name}_{species}_STARtmp/")
#        ),
```

Once I did that, the program ran smoothly across all samples.

Is this an issue you've encoutered before? If so, it might be worth commenting out those lines in the distribution code.

**Comment by J0bbie** [comment]
Hi Pietro,

I checked with several samples and I did have that folder generated (and automatically removed). Which STAR parameters are you using?

These settings (in the `config.yaml`) seem to work:
`  star: "--soloMultiMappers EM --outSAMmultNmax 1 --outSAMstrandField intronMotif --outSAMunmapped Within --outSAMattributes NH HI AS nM NM MD jM jI MC ch XS CR UR GX GN sM"
`

**Comment by plhm** [comment]
Hey, J0bbie.

I agree that the folder should be automatically removed. The issue wasn't STAR, at least not for me. The issue that for some reason the pipeline was expecting to see that folder after STAR finished running, which was leading it to crash. Once I removed the line I mentioned above, than the software stopped looking for 'dir_tmp,' and the program ran without any issues.

**Comment by J0bbie** [comment]
The newest version of the pipeline is running until the end without any missing files.
Please let me know if you do get this error again!
