### ISSUE TITLE
PhiX Spike in Lane - Biasing QC

### ISSUE THREAD

**Issue by plhm** [odomlab2/sci-rocket#22]
Hey, J0bbie.

I ran into another small issue over the break.

When we sent our sample out for sequencing to Novogene, they did a 15% PhiX spike to increase the complexity of the library, and reduce some issues they claimed to be having during sequencing. As a consequence, approximately 15% of my samples have a GGGGGGGGGG + AGATCTCGGT oligo combo for p7 and p5. This is throwing off a lot of the QCs in the pipeline, rightfully so, making the library look worse than what it is. Importantly, it is making it hard for me to see the actual degree of sequencing issues in my rt, ligation, p5 and p7 adaptors.

Is there anyway you could add somewhere in the pipeline a place in which the user could tell whether the lane has been split with sequences other than those from sci? I can see something like a black list which the software would ignore, and not count as mismatching oligos or anything along those lines.

This would be useful both in the bcl2fastq step, but also if one starts straight from the fastq files (assuming the user doesn't know how to drop those reads in their fastq).

P

**Comment by J0bbie** [comment]
Hi Pietro,

I'll think about the best way to adopt this whilst still keeping it general.
Thanks for all the suggestions.

Best,

Job
